### ISSUE TITLE
Non Mac installation

### ISSUE THREAD

**Issue by lpinner** [ptsefton/chordprobook#28]
I know we're on our own on other platforms :)

Just sharing some installation instructions that worked for me on Linux (and would possibly work on Win/MacOS as well)

Install conda ([miniconda](https://conda.io/miniconda.html) will do).
Create a conda environment, activate it and pip install chordprobook from github:
```
conda create -c conda-forge -n chordprobook python=3 pypandoc wkhtmltopdf pillow pyaml
source activate chordprobook
pip install git+https://github.com/ptsefton/chordprobook.git
```
Note: conda-forge channel is needed for wkhtmltopdf

Thanks for this tool, you rock

**Comment by ptsefton** [comment]
Thanks!

What are you using it for?

**Comment by lpinner** [comment]
I find it easier to write out songs for uke and guitar in tab/chords above format (and most of what's available on the net is in this format also), but prefer using chords inline for compactness. 

So I connected a script to convert from tab to chordpro and your tool to my code editor so I can write the tab and and then hit a keyboard shortcut to convert to chordpro and then PDF.

**Comment by ptsefton** [comment]
Added your instructions to the README, branch bug/fixdocx

**Comment by Axel-Erfurt** [comment]
dist-info name is wrong 

> pip3 install --user git+https://github.com/ptsefton/chordprobook.git
> Collecting git+https://github.com/ptsefton/chordprobook.git
>   Cloning https://github.com/ptsefton/chordprobook.git to ./pip-req-build-crprpuyw
>   Running command git clone -q https://github.com/ptsefton/chordprobook.git /tmp/pip-req-build-crprpuyw
> Collecting pypandoc
>   Downloading https://files.pythonhosted.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz
> Requirement already satisfied: pillow in /home/brian/.local/lib/python3.6/site-packages (from UNKNOWN==0.1) (6.2.1)
> Collecting pyaml
>   Downloading https://files.pythonhosted.org/packages/33/1a/936074f3492156693fc9e471269fc5747fa3b7d9d7f8a33af054f6b24066/pyaml-19.4.1-py2.py3-none-any.whl
> Requirement already satisfied: setuptools in /home/brian/.local/lib/python3.6/site-packages (from pypandoc->UNKNOWN==0.1) (41.4.0)
> Requirement already satisfied: pip>=8.1.0 in /home/brian/.local/lib/python3.6/site-packages (from pypandoc->UNKNOWN==0.1) (19.3.1)
> Requirement already satisfied: wheel>=0.25.0 in /home/brian/.local/lib/python3.6/site-packages (from pypandoc->UNKNOWN==0.1) (0.33.6)
> Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from pyaml->UNKNOWN==0.1) (3.12)
> Building wheels for collected packages: UNKNOWN, pypandoc
>   Building wheel for UNKNOWN (setup.py) ... done
>   Created wheel for UNKNOWN: filename=UNKNOWN-0.1-cp36-none-any.whl size=62357 sha256=1fa8ad1afd589d17ebc065b1b7aa27d86310bced479f0c7481d7643cb10e04c0
>   Stored in directory: /tmp/pip-ephem-wheel-cache-1w9vly8j/wheels/fc/cf/c2/c633763d2e861510457464b347ee723dd8018aa2e6709789ab
>   Building wheel for pypandoc (setup.py) ... done
>   Created wheel for pypandoc: filename=pypandoc-1.4-cp36-none-any.whl size=16465 sha256=007520157680e67ca5724a7042fbee83588e9e19d882f2b08bca300ad861a417
>   Stored in directory: /home/brian/.cache/pip/wheels/3e/55/4f/59e0fa0914f3db52e87c0642c5fb986871dfbbf253026e639f
> Successfully built UNKNOWN pypandoc
> Installing collected packages: pypandoc, pyaml, UNKNOWN
> Successfully installed UNKNOWN-0.1 pyaml-19.4.1 pypandoc-1.4

_~/.local/lib/python3.6/site-packages/chordprobook/_  is ok

I have renamed UNKNOWN-0.1.dist-info in ~/.local/lib/python3.6/site-packages/ to chordprobook-0.1.dist-info

then _pip3 show chordprobook_ gives a result

> Name: chordprobook
> Version: 0.1
> Summary: Chordpro songsheet and book generator
> Home-page: https://github.com/ptsefton/chordprobook
> Author: Peter Sefton
> Author-email: pt@ptsefton.com
> License: UNKNOWN
> Location: /home/brian/.local/lib/python3.6/site-packages
> Requires: pyaml, pillow, pypandoc
> Required-by: 
>
