### ISSUE TITLE
Feature Request: Convert from other formats back to chordpro

### ISSUE THREAD

**Issue by joshuadanpeterson** [ptsefton/chordprobook#31]
While pdf, HTML, and doc are great human-readable formats, it'd be great if it were possible to convert these filetypes to chordpro for easy manipulation. Not all chord charts align properly over lyrics so I know this might be a bit of a pain, but even if the script gets some of the basic formatting and syntax right in the conversion to at least get the user half-way there, the time save would be worth it.

**Comment by ptsefton** [comment]
Do you have an example of anything you'd like to convert?

**Comment by ptsefton** [comment]
Closing due to lack of interest
